<a href="https://colab.research.google.com/github/jyothisriprabhakargit/machine_learning_and_data_science_My_Work/blob/main/ML_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


Numpy
. It means numerical python
. It's the linear algebra

Python idle

pip installe numpy

Anaconda

conda installe numpy

In [ ]:
my_list=[1,2,3]

In [ ]:
import numpy as np

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
arr=np.array(my_list)

In [ ]:
arr

array([1, 2, 3])

Creating matrix

In [ ]:
my_mat=[[1, 2,3], [4, 5,6], [7,8,9]]

In [ ]:
np. array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ap evenly spaced array

In [ ]:
np. arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In AP format 

Different of 2
(0, 20,2)

In [ ]:
np. arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

Linespace

Start 1

End 2

Linespace 5

Eg 1,1.2,1.4,1.6,1.8

In [ ]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Identity matrices


Matrix n*m for I: n==m

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array of random numbers

rand


N element between 0and 1

In [ ]:
np.random.rand(5)

array([0.95031661, 0.89264854, 0.2285205 , 0.0327742 , 0.08803624])

randn


N element with standard distribution

In [ ]:
np.random.randn(2)

array([ 0.91370723, -0.61612793])

randint

Get integers values

In [ ]:
np.random.randint(0,10)

1

In [ ]:
np.random.randint(0,100,10)

array([29, 45, 10, 43, 29, 34, 43, 57, 45, 65])